### ISSUE TITLE
Any chance of sharing the slides for Rich Hickey's  Simple Made Easy talk?

### ISSUE THREAD

**Issue by martisj** [strangeloop/2011-slides#10]
Link to the talk here: https://www.infoq.com/presentations/Simple-Made-Easy

**Comment by puredanger** [comment]
You may find this helpful. https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/SimpleMadeEasy.md

**Comment by puredanger** [comment]
I don't have the slides to share them
