### ISSUE TITLE
Davis-MobileHTML5.pdf has zero bytes

### ISSUE THREAD

**Issue by agemooij** [strangeloop/2011-slides#7]
Hi Alex, thanks for the great conference!

I noticed that the _Davis-MobileHTML5.pdf_ file has zero bytes. Hopefully you can fix that because I missed it last week and I heard that it was a great talk.

Looking forward to the videos. 

Regards,
Age Mooij
[@agemooij](http://twitter.com/agemooij)
age.mooij@gmail.com

**Comment by gliptak** [comment]
Cashion-Chloe.pdf is zero bytes too. Thanks

**Comment by puredanger** [comment]
@agemooij - I'm working on getting it from Scott. 

@gliptak - it's just really big - if you do "git clone git://github.com/strangeloop/2011-slides.git" you can grab the whole repo.  I'll try to get a smaller version soon.

**Comment by gliptak** [comment]
Thank you Alex

**Comment by puredanger** [comment]
@agemooij - now available as well as a low-res version.

@gliptak - now available as a smaller version (but still might be too big to get through the web interface)

**Comment by agemooij** [comment]
Thanks Alex!
