### ISSUE TITLE
Error: blob is too big

### ISSUE THREAD

**Issue by rschildmeijer** [strangeloop/2011-slides#8]
Tried to download LewisShip-MetaprogrammingJava.pdf. Received "Error: blob is too big"

**Comment by agemooij** [comment]
You will get that one for quite a few presentations since Github has some kind of hard limit on file sizes that they allow to be accessed through their web layer. The solution is to just clone the repository and let Git do the hard work for you.

**Comment by puredanger** [comment]
Yes: do "git clone git://github.com/strangeloop/2011-slides.git" to grab everything OR I have now uploaded a lower-res version of Howard's talk: LewisShip-MetaprogrammingJava-small.pdf.
